apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-config
  namespace: javapg
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres

---
apiVersion: v1
kind: Secret
metadata:
  name: spring-secrets
  namespace: javapg
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: javapg
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: mariopet/java-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: spring-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: spring-secrets
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-secrets
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: spring-app
  namespace: javapg
spec:
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spring-ingress
  namespace: javapg
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-app
                port:
                  number: 8080
